# Dependencies
markdown:    kramdown
highlighter: rouge

# Permalinks
permalink:   pretty

# Setup
name:        KotlinBlog.com
title:       KotlinBlog.com
tagline:     'A blog about Kotlin programming language.'
description: 'A blog about <a href="https://kotlinlang.org/" target="_blank">Kotlin</a> programming language. Made by a <a href="http://kotlinblog.com/about" target="_blank">mobile developer</a> tired of Java.'
url:         http://kotlinblog.com
baseurl:     http://kotlinblog.com/

author:
  name:      'Jan Slominski'
  url:       http://kotlinblog.com

paginate:    5

github:
  repo:      https://github.com/slomin

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist

# Outputting
permalink: /:categories/:year/:month/:day/:title/
